LuxyGaming/Models/Base.cs
namespace LuxyGaming.Models
{
    public class Base
    {
        public int Id { get; set; }
    }
}

LuxyGaming/Models/Category.cs
namespace LuxyGaming.Models
{
    public class Category:Base
    {
        public required string Name { get; set; }
        public required string ImageUrl { get; set; }
    }
}

LuxyGaming/Models/Contact.cs
namespace LuxyGaming.Models
{
    public class Contact : Base
    {
        public string Title { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }


      
  
    }
}

LuxyGaming/Models/DataAccess/LuxyDbContext.cs
using LuxyGaming.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LuxyGaming.Models.DataAccess
{
    public class LuxyDbContext: DbContext
    {
        public LuxyDbContext(DbContextOptions<LuxyDbContext> options) : base(options) { }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<MainGame> MainGames { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Games>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Price)
                      .HasColumnType("decimal(18,2)");
                entity.Property(e => e.Discount)
                      .HasColumnType("decimal(18,2)");
            });
        }

      
    }
}

LuxyGaming/Models/ErrorViewModel.cs
namespace LuxyGaming.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LuxyGaming/Models/Games.cs
namespace LuxyGaming.Models
{
    public class Games:Base
    {
        public required string Name { get; set; }
        public required string  ImageUrl { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public bool IsTrend { get; set; }
        public bool IsMostPlayed { get; set; }
        public  Category? Category { get; set; }
        public int CategoryId { get; set; }
    }
}

LuxyGaming/Models/MainGame.cs
namespace LuxyGaming.Models
{
    public class MainGame : Base
    {
        public string Title { get; set; }=string.Empty;
        public string Summary { get; set; }=string.Empty;
        public string ImageUrl { get; set; } = string.Empty;
        public double Price { get; set; }
        public double Discount { get; set; }
    }
}

LuxyGaming/Controllers/ContactController.cs
using LuxyGaming.Models;
using LuxyGaming.Models.DataAccess;
using Microsoft.AspNetCore.Mvc;

namespace LuxyGaming.Controllers
{
    public class ContactController : Controller
    {
        private readonly LuxyDbContext _dbContext;

        public ContactController(LuxyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View(_dbContext.Contacts.FirstOrDefault());
        }
    }
}

LuxyGaming/Controllers/HomeController.cs
using LuxyGaming.Models;
using LuxyGaming.Models.DataAccess;
using LuxyGaming.VieewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace LuxyGaming.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly LuxyDbContext _dbContext;
        public HomeController(ILogger<HomeController> logger, LuxyDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
 
      
            HomeVM homeVM = new HomeVM() 
            {
                MainGame = _dbContext.MainGames.FirstOrDefault(),
                Categories= _dbContext.Categories.ToList(),
                TrendGames=_dbContext.Games.Where(x=>x.IsTrend).Take(4).ToList(),
                MostPlayedGames=_dbContext.Games.Where(x=>x.IsMostPlayed).Take(6).ToList(),
            };
            return View(homeVM);
        }

        public IActionResult Detail(int? id)
        {
            var game = _dbContext.Games.FirstOrDefault(x => x.Id == id);
            var categories = _dbContext.Categories.ToList();
            if (game == null)
            {
                return NotFound();
            }

            ProdcutDetailVM prodcutDetailVM = new ProdcutDetailVM()
            {
                GameDetail = _dbContext.Games.FirstOrDefault(x => x.Id == id),
                RelatedGames = _dbContext.Games.Where(x => x.CategoryId == game.CategoryId).ToList(),
                Categories=categories,
            };
            return View(prodcutDetailVM);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LuxyGaming/Controllers/ShopController.cs
using LuxyGaming.Models;
using LuxyGaming.Models.DataAccess;
using LuxyGaming.VieewModels;
using Microsoft.AspNetCore.Mvc;

namespace LuxyGaming.Controllers
{
    public class ShopController : Controller
    {
        private readonly LuxyDbContext _dbContext;

        public ShopController(LuxyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index(string? category)
        {
            Category selectedCategory = null;

            if (category != null)
            {
                selectedCategory = _dbContext.Categories.FirstOrDefault(x => x.Name == category);
            }

            if (category == "All")
            {
                selectedCategory = null;
            }
            ShopVM shopVM = new ShopVM()
            {
                Categories = _dbContext.Categories.ToList(),
                Games = _dbContext.Games.ToList(),
                SelectedCategory = selectedCategory,
            };
            return View(shopVM);
        }
    }
}

LuxyGaming/Views/Contact/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Contact Page";
}
<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Contact Us</h3>
                <span class="breadcrumb"><a href="#">Home</a>  >  Contact Us</span>
            </div>
        </div>
    </div>
</div>

<div class="contact-page section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 align-self-center">
                <div class="left-text">
                    <div class="section-heading">
                        <h6>@Model.Title</h6>
                        <h2>@Model.Text</h2>
                    </div>
                    <p>@Model.Description</p>
                    <ul>
                        <li><span>Address</span> @Model.Address</li>
                        <li><span>Phone</span> @Model.Phone</li>
                        <li><span>Email</span> @Model.Email</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="map">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth" width="100%" height="325px" frameborder="0" style="border:0; border-radius: 23px;" allowfullscreen=""></iframe>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <form id="contact-form" action="" method="post">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input type="name" name="name" id="name" placeholder="Your Name..." autocomplete="on" required>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input type="surname" name="surname" id="surname" placeholder="Your Surname..." autocomplete="on" required>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input type="text" name="email" id="email" pattern="" placeholder="Your E-mail..." required="">
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input type="subject" name="subject" id="subject" placeholder="Subject..." autocomplete="on">
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-12">
                                        <fieldset>
                                            <textarea name="message" id="message" placeholder="Your Message"></textarea>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-12">
                                        <fieldset>
                                            <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                                        </fieldset>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  

LuxyGaming/Views/Home/Detail.cshtml
@model ProdcutDetailVM

<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>@Model.GameDetail.Name</h3>
                <span class="breadcrumb"><a href="/">Home</a>  >  <a asp-controller="Shop" asp-action="Index">Shop</a>  >@Model.GameDetail.Name</span>
            </div>
        </div>
    </div>
</div>

<div class="single-product section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-image">
                    <img src="~/assets/images/@Model.GameDetail.ImageUrl" alt="defaultImage">
                </div>
            </div>
            <div class="col-lg-6 align-self-center">
                <h4>@Model.GameDetail.Name</h4>
                <span class="price"><em>$@Model.GameDetail.Price</em> $@Model.GameDetail.Discount</span>
                <form id="qty" action="#">
                    <input type="qty" class="form-control" id="1" aria-describedby="quantity" placeholder="1">
                    <button type="submit"><i class="fa fa-shopping-bag"></i> ADD TO CART</button>
                </form>
                <ul>
                    <li><span>Game ID:</span> @Model.GameDetail.Id</li>
                    <li><span>Category:</span> @Model.Categories.FirstOrDefault(x => x.Id == @Model.GameDetail.CategoryId)?.Name</li>
                    <li><span>Multi-tags:</span> <a href="#">War</a>, <a href="#">Battle</a>, <a href="#">Royal</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="sep"></div>
            </div>
        </div>
    </div>
</div>

<div class="more-info">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-content">
                    <div class="row">
                        <div class="nav-wrapper">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false">Reviews (3)</button>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                                <p>You can search for more templates on Google Search using keywords such as "templatemo digital marketing", "templatemo one-page", "templatemo gallery", etc. Please tell your friends about our website. If you need a variety of HTML templates, you may visit Tooplate and Too CSS websites.</p>
                            </div>
                            <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                                <p>Reviews content here...</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section categories related-games">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading">
                    <h6>@Model.Categories.FirstOrDefault(x => x.Id == @Model.GameDetail.CategoryId)?.Name</h6>
                    <h2>Related Games</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="main-button">
                    <a href="shop.html">View All</a>
                </div>
            </div>
            @foreach (Games game in Model.RelatedGames)
            {
                <div class="col-lg col-sm-6 col-xs-12">
                    <div class="item">
                        <h4>@game.Name</h4>
                        <div class="thumb">
                            <a asp-controller="Home" asp-action="Detail" asp-route-id="@game.Id"><img width="300px" height="300px" src="~/assets/images/@game.ImageUrl" alt=""></a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

LuxyGaming/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model HomeVM;

<div class="main-banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 align-self-center">
                <div class="caption header-text">
                    <h6>Welcome to lugx</h6>
                    <h2>@Model.MainGame.Title!</h2>
                    <p>@Model.MainGame.Summary.</p>
                    <div class="search-input">
                        <form id="search" action="#">
                            <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                            <button role="button">Search Now</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-2">
                <div class="right-image">
                    <img src="~/assets/images/@Model.MainGame.ImageUrl" alt="">
                    <span class="price">$@Model.MainGame.Price</span>
                    <span class="offer">-@Model.MainGame.Discount%</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="features">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <a href="#">
                    <div class="item">
                        <div class="image">
                            <img src="~/assets/images/featured-01.png" alt="" style="max-width: 44px;">
                        </div>
                        <h4>Free Storage</h4>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#">
                    <div class="item">
                        <div class="image">
                            <img src="~/assets/images/featured-02.png" alt="" style="max-width: 44px;">
                        </div>
                        <h4>User More</h4>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#">
                    <div class="item">
                        <div class="image">
                            <img src="~/assets/images/featured-03.png" alt="" style="max-width: 44px;">
                        </div>
                        <h4>Reply Ready</h4>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#">
                    <div class="item">
                        <div class="image">
                            <img src="~/assets/images/featured-04.png" alt="" style="max-width: 44px;">
                        </div>
                        <h4>Easy Layout</h4>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="section trending">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading">
                    <h6>Trending</h6>
                    <h2>Trending Games</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="main-button">
                    <a href="shop.html">View All</a>
                </div>
            </div>
            @foreach(Games games in Model.TrendGames)
            {
                <div class="col-lg-3 col-md-6">
                    <div class="item">
                        <div class="thumb">
                            <a asp-controller="Home" asp-action="Detail" asp-route-id="@games.Id"><img width="300px" height="300px" src="~/assets/images/@games.ImageUrl" alt=""></a>
                            <span class="price"><em>$@games.Price</em>$@games.Discount</span>
                        </div>
                        <div class="down-content">
                            <span class="category">@Model.Categories.FirstOrDefault(x=>x.Id==games.CategoryId).Name</span>
                            <h4>@games.Name</h4>
                            <a asp-controller="Home" asp-action="Detail" asp-route-id="@games.Id"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
            }

        
    </div>
</div>

<div class="section most-played">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading">
                    <h6>TOP GAMES</h6>
                    <h2>Most Played</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="main-button">
                    <a href="shop.html">View All</a>
                </div>
            </div>
                @foreach (Games game in Model.MostPlayedGames)
                {
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="item">
                            <div class="thumb">
                                <a asp-controller="Home" asp-action="Detail" asp-route-id="@game.Id"><img width="300px" height="250px" src="~/assets/images/@game.ImageUrl" alt=""></a>
                            </div>
                            <div class="down-content">
                                <span class="category">@Model.Categories.FirstOrDefault(x=>x.Id==game.CategoryId).Name</span>
                                <h4>@game.Name</h4>
                                <a asp-controller="Home" asp-action="Detail" asp-route-id="@game.Id">Explore</a>
                            </div>
                        </div>
                    </div>

                }
       
        </div>
    </div>
</div>

<div class="section categories">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-heading">
                    <h6>Categories</h6>
                    <h2>Top Categories</h2>
                </div>
            </div>

            @foreach (var item in Model.Categories)
            {
                <div class="col-lg col-sm-6 col-xs-12">
                    <div class="item">
                        <h4>@item.Name</h4>
                        <div class="thumb">
                            <a href="#"><img src="~/assets/images/@item.ImageUrl" alt=""></a>
                        </div>
                    </div>
                </div>

            }
 
        </div>
    </div>
</div>

<div class="section cta">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="shop">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="section-heading">
                                <h6>Our Shop</h6>
                                <h2>Go Pre-Order Buy & Get Best <em>Prices</em> For You!</h2>
                            </div>
                            <p>Lorem ipsum dolor consectetur adipiscing, sed do eiusmod tempor incididunt.</p>
                            <div class="main-button">
                                <a href="shop.html">Shop Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-2 align-self-end">
                <div class="subscribe">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="section-heading">
                                <h6>NEWSLETTER</h6>
                                <h2>Get Up To $100 Off Just Buy <em>Subscribe</em> Newsletter!</h2>
                            </div>
                            <div class="search-input">
                                <form id="subscribe" action="#">
                                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your email...">
                                    <button type="submit">Subscribe Now</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LuxyGaming/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LuxyGaming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LuxyGaming.styles.css" asp-append-version="true" />
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-lugx-gaming.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="/" alt="" style="width: 158px;">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="/" asp-active-route="Home">Home</a></li>
                            <li><a asp-action="Index" asp-controller="Shop" asp-active-route="Shop">Our Shop</a></li>
                            <li><a asp-controller="Contact" asp-action="Index" asp-active-route="Contact">Contact Us</a></li>
                            <li><a href="#">Sign In</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            <div class="col-lg-12">
                <p>Copyright © 2048 LUGX Gaming Company. All rights reserved. &nbsp;&nbsp; <a rel="nofollow" href="https://templatemo.com" target="_blank">Design: TemplateMo</a></p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/js/isotope.min.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/counter.js"></script>
    <script src="~/assets/js/custom.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LuxyGaming/Views/Shop/Index.cshtml
@model ShopVM
<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Our Shop</h3>
                <span class="breadcrumb"><a href="/">Home</a> > Our Shop</span>
            </div>
        </div>
    </div>
</div>

<div class="section trending">
    <div class="container">
        <ul class="trending-filter">
            <li>
                <a href="@Url.Action("Index", "Shop", new { category = "All" })" data-filter="*">Show All</a>
            </li>
            @foreach (Category category in Model.Categories)
            {
                <li>
                    <a href="@Url.Action("Index", "Shop", new { category = category.Name })" data-filter=".cat-@category.Id">@category.Name</a>
                </li>
            }
        </ul>
        <div class="row trending-box">
            @if (Model.SelectedCategory != null)
            {
                foreach (Games game in Model.Games.Where(x => x.CategoryId == Model.SelectedCategory.Id))
                {
                    <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 cat-@game.CategoryId">
                        <div class="item">
                            <div class="thumb">
                                <a href="product-details.html"><img width="300PX" height="300px"  src="~/assets/images/@game.ImageUrl" alt=""></a>
                                <span class="price"><em>$@game.Price</em>$@game.Discount</span>
                            </div>
                            <div class="down-content">
                                <span class="category">@Model.Categories.FirstOrDefault(c => c.Id == game.CategoryId)?.Name</span>
                                <h4>@game.Name</h4>
                                <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                foreach (Games game in Model.Games)
                {
                    <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 cat-@game.CategoryId">
                        <div class="item">
                            <div class="thumb">
                                <a href="product-details.html"><img width="300PX" height="300px" src="~/assets/images/@game.ImageUrl" alt=""></a>
                                <span class="price"><em>$@game.Price</em>$@game.Discount</span>
                            </div>
                            <div class="down-content">
                                <span class="category">@Model.Categories.FirstOrDefault(c => c.Id == game.CategoryId)?.Name</span>
                                <h4>@game.Name</h4>
                                <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
        <div class="row">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li><a href="#"> &lt; </a></li>
                    <li><a href="#">1</a></li>
                    <li><a class="is_active" href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#"> &gt; </a></li>
                </ul>
            </div>
        </div>
    </div>
</div>